# Generated by Django 5.0.4 on 2025-10-27 02:50

import backend.features.sample.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.CharField(default=backend.features.sample.models.generate_sample_id, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('bam_url', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_id', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'samples',
                'ordering': ['-created_at'],
            },
        ),
    ]
